server:
    port: 8080

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8099/eureka/

spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enable: true
            routes:
                - id: service-service
                  uri: lb://service-service
                  predicates:
                    - Path=/stuff/**
                - id: client-service
                  uri: lb://client-service
                  predicates:
                    - Path=/client/**
